name: Publish to main

on: 
  repository_dispatch: 
  push: 
    branches: 
      - main
    
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: Use Node.js 
      uses: actions/setup-node@v1 
      with: 
        node-version: '12.x' 
    - run: yarn 
    - run: yarn run build 
    - name: Deploy 
      uses: peaceiris/actions-main@v3 
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        publish_dir: ./build 
    - name: HTML Preview
  # You may pin to the exact commit or the version.
  # uses: pavi2410/html-preview-action@9420cd81fbbe0035f59a39536ea5a0443daffa37
  uses: pavi2410/html-preview-action@v2
  with:
    # The HTML file you want to preview, relative to the root of the repo
    html_file: # default is index.html
